version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: composer
    directory: /src
    schedule:
      interval: weekly

  - package-ecosystem: pnpm
    directory: /src
    schedule:
      interval: weekly
